# /usr/bin/env python2
# Encoding: UTF-8
"""\
Note: This script worked, but is extremely slow.

Highly divisible triangular number
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

def triangle_numbers():
    total = 0
    i = 1
    while True:
        total += i
        i += 1
        yield total

def count_factors(number):
    amount = 1
    for i in xrange(1, number/2+1):
        if number % i == 0:
            amount +=1
    return amount

for cnt, number in enumerate(triangle_numbers()):
    amt = count_factors(number)
    if amt > 500:
        print "FOUND IT!", number
        break
    elif cnt % 100 == 0:
        print cnt, number, amt
